-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjFMolvuzrpLHFQN+
ikWngDRnsvmhxZlmkdTr+JXVgLigCgYIKoZIzj0DAQehRANCAAQdQPEFRqwezaZ2
H36ohIWKQahvwZ+U1iOfGv7Tr9obbwaagPCVCtFriWlDqeU/wGTNuM7z2I9e+iWr
lratnZ2Y
-----END PRIVATE KEY-----